### ISSUE TITLE
Ray not receiving events anymore

### ISSUE THREAD

**Issue by io238** [spatie/ray#559] opened 2021-09-15 11:27 UTC
**Describe the bug**
Ray does not receive any events anymore. It used to work in the past, but has stopped working now. I don't recall making any changes to the setup/environment.

**Versions**
- Ray version: 1.17.0.0 (Win)
- spatie/ray package version: 1.30.2
- spatie/laravel-ray package version: 1.25.2

PHP version: 8.0.10
Laravel version: 8.61.0

**To Reproduce**
1. Open tinker
2. Send test via `ray('Hello World');`

**Expected behavior**
Test string should appear in Ray.

**Screenshots**
No output received by Ray
![image](https://user-images.githubusercontent.com/26689138/133424001-06e4b27e-5fc1-4e20-8df2-6297635c2daa.png)

**Output by RayProxy**
https://github.com/permafrost-dev/ray-proxy

```
{"level":30,"time":1631702904516,"pid":580,"hostname":"152784d7f7e8","reqId":"req-5","res":{"statusCode":404},"responseTime":259.6536000003107,"msg":"request completed"}
{"level":30,"time":1631702904519,"pid":580,"hostname":"152784d7f7e8","reqId":"req-6","req":{"method":"POST","url":"/","hostname":"localhost:23517","remoteAddress":"127.0.0.1","remotePort":33790},"msg":"incoming request"}
{"level":50,"time":1631702904520,"pid":580,"hostname":"152784d7f7e8","reqId":"req-6","req":{"method":"POST","url":"/","hostname":"localhost:23517","remoteAddress":"127.0.0.1","remotePort":33790},"res":{"statusCode":500},"err":{"message":"connect ECONNREFUSED 127.0.0.1:23516","stack":"Error: connect ECONNREFUSED 127.0.0.1:23516\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)","config":{"url":"http://localhost:23516","method":"post","data":"{\"uuid\":\"3f791b93-3e49-4e36-813c-17c719c4bbf1\",\"payloads\":[{\"type\":\"log\",\"content\":{\"values\":[\"Hello world\"]},\"origin\":{\"file\":\"/var/www/html/vendor/psy/psysh/src/ExecutionLoopClosure.php(55) : eval()'d code\",\"line_number\":1,\"hostname\":\"152784d7f7e8\"}}],\"meta\":{\"php_version\":\"8.0.10\",\"php_version_id\":80010,\"laravel_version\":\"8.61.0\",\"laravel_ray_package_version\":\"1.25.2.0\",\"ray_package_version\":\"1.30.2.0\"}}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.21.4","Content-Length":410},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"ECONNREFUSED"},"msg":"connect ECONNREFUSED 127.0.0.1:23516"}
{"level":30,"time":1631702904521,"pid":580,"hostname":"152784d7f7e8","reqId":"req-6","res":{"statusCode":500},"responseTime":1.8287999997846782,"msg":"request completed"}
```

**Desktop:**
 - OS: Win10 (running WSL2 / Ubuntu 20.04)

**Comment by io238** [comment] 2021-09-15 11:32
![image](https://user-images.githubusercontent.com/26689138/133425689-d22d0ed2-428c-4ff3-87a4-fee5a1dc9530.png)

**Comment by hypnotox** [comment] 2021-09-23 12:06
I have the same problem since i tried to use it a few days ago. No changes to the setup.
It has worked without any problems before.

Version: 1.17.0
OS: macOS 11.4

I tried it with spatie/ray and spatie/laravel-ray.
Port 23517 is assigned to the process and listening.

**Comment by AdrianMrn** [comment] 2021-09-27 10:43
There haven't been any changes to the way logs are sent or received in quite a while. Could you please try uninstalling the app and reinstalling it, and trying to send messages in a new, clean Laravel app?

**Closed by AdrianMrn** 2021-09-27 10:43 UTC

**Comment by io238** [comment] 2021-09-27 12:19
I reinstalled the app + also reinstalled Ray into a fresh Laravel app. Still did not work for any project within Docker, nevertheless, I was able to send messages directly from Windows (w/o using Docker).

I was able to get it working again by publishing a fresh version of the docker config into the project root with `php artisan ray:publish-config --docker`.

Other than [stated in the docs](https://spatie.be/docs/ray/v1/configuration/general), Ray does not seem to be picking up the `ray.php`, if it's stored in a parent directory.

**Comment by AdrianMrn** [comment] 2021-09-28 09:17
@freekmurze is this something we need to push a fix for?

**Comment by freekmurze** [comment] 2021-09-28 10:17
We'll need to see if we can reproduce this.
I think we already have a couple of tests that prove that `ray.php` is getting picked up a parent directory.

I'll take a look soon.

**Comment by ryanmortier** [comment] 2021-11-03 19:45
I just installed Ray for the first time today with Windows and WSL2. I followed the WSL2 instructions in the docs and wondering if this is related to this issue.

I've set a static IP for my windows host and have the IP set in my .env file with the `RAY_HOST` variable.

Inside WSL2 I'm able to connect to ray:

```
➜  export git:(develop) ✗ telnet 10.0.0.100 23517
Trying 10.0.0.100...
Connected to 10.0.0.100.
Escape character is '^]'.
```

However, when I try to run `ray('test')`, nothing appears.

**Comment by ryanmortier** [comment] 2021-11-04 14:50
@AdrianMrn can this be reopened?

**Comment by AdrianMrn** [comment] 2021-11-04 15:34
Hi @ryanmortier, could you please open a new issue with the information from your above comment? We like to keep these kind of issues separate, in case they're not entirely related to the same cause. This way, you'll also fill out the issue template, and we get more information to help us debug this problem.

Feel free to refer to this issue when creating yours.
