### ISSUE TITLE
Cannot see whole sql query

### ISSUE THREAD

**Issue by semiherdogan** [spatie/ray#149] opened 2021-01-13 20:19 UTC
**Describe the bug**
I cannot see whole sql query if query is too long.

**Versions**
Ray version 1.2.5

**To Reproduce**
1. Log a query with long parameters. 

**Expected behavior**
Maybe adding horizontal scrolling into sql query area may fix this issue.

**Screenshots**
<img width="862" alt="Screen Shot 2021-01-13 at 23 10 14" src="https://user-images.githubusercontent.com/5646041/104505369-d2167380-55f4-11eb-98d4-41e35db5eda8.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.1 (Big Sur)
 
 **Additional context**
I can copy whole sql query into clipboard by clicking the copy button. It's working as expected.

**Comment by willemvb** [comment] 2021-01-19 09:50
Duplicate of https://github.com/spatie/laravel-ray/issues/77

**Closed by willemvb** 2021-01-19 09:50 UTC
