### ISSUE TITLE
Ray seems not be running at http://localhost:23517

### ISSUE THREAD

**Issue by atiqsamtia** [spatie/ray#38] opened 2021-01-08 08:52 UTC
**Describe the bug**
Ray seems not be running at http://localhost:23517

Request takes time to process and fails to this message. If in this time I open ray app, everything works just fine.

Happening on Windows 10 with laragon.

**Versions**
Ray version: 1.0.2.0
spatie/ray package version: 1.1.3
spatie/laravel-ray package version (if applicable): 1.1
Laravel version (if applicable): 8.12
Media Library Pro version: N/A

**To Reproduce**
1. Create a new laravel app
2. Install laravel-ray package
3. Add one ray() statement in web.php
4. Quit ray Windows App
5. Open laravel default home route.

**Expected behavior**
As this is an optional developer tool, if ray app is not running, Laravel application should run just fine without considering ray helper just like it runs in prpduction.

**Screenshots**
![image](https://user-images.githubusercontent.com/5112753/103993717-d6d3c580-51b7-11eb-8f82-27fb033450b3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 
 **Additional context**

**Comment by ronnievisser** [comment] 2021-01-08 09:00
Got this same error when running on Homestead on a Mac.. Does it work with homestead?

**Comment by freekmurze** [comment] 2021-01-08 09:02
I'll try to reproduce this soon.

@ronnievisser could you try this: https://twitter.com/JoePFerguson/status/1347302653127237634

**Comment by ronnievisser** [comment] 2021-01-08 09:05
@freekmurze It does not make any difference!

**Comment by laemol** [comment] 2021-01-08 09:23
I have the same error running on mac with Valet+ even without adding the ray() statement but just with an (known) error in my project. Starting the Ray App also solved it and shows the error in Ray.

**Comment by maciejsk** [comment] 2021-01-08 09:58
...after uninstall and install again it work (1.0.3).

**Comment by ronnievisser** [comment] 2021-01-08 10:45
for homestead:

"Create a ray.php config file at project root and copy the boiler config from the ray docs and then set the host in the config to 10.0.2.2 and it should work."

works

**Comment by freekmurze** [comment] 2021-01-08 10:52
Closing this as people are reporting that it works now.

**Comment by freekmurze** [comment] 2021-01-08 10:52
If this is still a problem using the latest versions, let me know!

**Closed by freekmurze** 2021-01-08 10:52 UTC

**Comment by atiqsamtia** [comment] 2021-01-08 11:01
@freekmurze did anyone test on Windows 10? I'm still unable to run laravel application if ray is not running

**Comment by laemol** [comment] 2021-01-08 11:01
Still having this with Valet+ 
"spatie/laravel-ray": "^1.1",
Version 1.0.3 (1.0.3)
Laravel Framework 8.16.1
When my application is trying to throw a error message now shows "Ray seems not be running at http://localhost:23517"
When Ray App is running I receive the expected error "InvalidArgumentException View [] not found."

**Comment by xyNNN** [comment] 2021-01-08 11:15
> ...after uninstall and install again it work (1.0.3).
> 
> oh my ray.php config
> 
> 'host.docker.internal', /* * The port number used to communicate with the Ray app. */ 'port' => 23517, ];

Doesn't work for me ... For some reason it can't communicate to my local computer.

Ray seems not be running at http://host.docker.internal:23517

**Comment by dib258** [comment] 2021-01-08 13:11
Opening the specific port Ray is using in Homestead.yaml configuration file
```yaml
ports:
     - send: 23517
       to: 23517
       protocol: tcp
```

Which is opened during the initialisation when restarting Homestead (and making `vagrant provision` before restarting it)
```
homestead-research: 23517 (guest) => 23517 (host) (adapter 1)
```

Retrieve the external ip of the host machine (from this SO : https://stackoverflow.com/a/44873282/2018745)
```bash
➜  route -n | grep 'UG[ \t]' | awk '{print $2}'
10.0.2.2
```

Copied the `ray.php` configuration file which is set to 
```php
<?php
[
    /*
     * The host used to communicate with the Ray app.
     * For usage in Docker on Mac or Windows, you can replace host with 'host.docker.internal'
     */
    'host' => '10.0.2.2',

    /*
     * The port number used to communicate with the Ray app.
     */
    'port' => 23517,
]
```

Checking from outside Homestead if something is listening to the port (Which must be Ray App)
```bash
➜  sudo netstat -an | grep LISTEN | grep 23517
tcp46      0      0  *.23517                *.*                    LISTEN
tcp4       0      0  *.23517                *.*                    LISTEN
```

Another way to watch if it's listening from outside of Homestead. And this command show the name of the app listening !
```bash
➜  sudo lsof -nP -iTCP:23517 | grep LISTEN
VBoxHeadl 46934 dib258   19u  IPv4 0x346ea245002b6341      0t0  TCP *:23517 (LISTEN)
Ray       47451 dib258   52u  IPv6 0x346ea244e5e0ab51      0t0  TCP *:23517 (LISTEN)
```

When I am loggued into the Homestead machine and everything of the above is working, I try to curl the Ray app and here is what I get :
```bash
➜  curl -X GET 10.0.2.2:23517
curl: (52) Empty reply from server
```

1. Is it normal ?
2. Shouldn't the app return something ? 
3. Could the VBoxHeadl intercept the value in some way ?

Is there another Curl command that I should try to see if it's getting ray to react ?

Thanks for you help ;)

**Comment by sevenpixels** [comment] 2021-01-08 19:38
Homestead.yaml updated just like @dib258 and same ray.php file.

- Ray 1.0.5
- spatie/ray: 1.3.2
- php 7.4.5

Simple script. I include the package, I call `ray('test')` but I get nothing in the Ray app. Originally I was on spatie/ray 1.1 and I would get `Ray seems not be running at http://10.0.2.2:23517` but now I don't even get that error.

**Comment by sevenpixels** [comment] 2021-01-10 05:20
No changes in the Homestead.yaml or the ray.php config. It's working now.

- Ray 1.0.7
- spatie/ray: 1.3.7

**Comment by dib258** [comment] 2021-01-10 10:47
I just tested removing the opening of the port in the `Homestead.yaml` (then `vagrant provision`, `vagrant halt` and `vagrant up`) file and it's actually working, so forcing Homestead to open the port is kind of adding some other tools listening to that port apparently that catch or block the request to Ray app. 

Thanks for the solution @sevenpixels ! ;)

If someone has an explanation why, it would be amazing for me to learn why the heck it was not working ! :p

**Comment by freekmurze** [comment] 2021-01-10 11:40
If there is anything that can be improved around this in our docs, let me know!

**Comment by laemol** [comment] 2021-01-10 11:52
Hi Freek, can you please fix the issue that Ray app needs te be running when working local?

**Comment by freekmurze** [comment] 2021-01-10 11:56
@laemol  afaik this is not a problem in the latest version of the package. Can you create a small app to recreate the problem and share that with me?

**Comment by dib258** [comment] 2021-01-10 12:14
@freekmurze I don't think there's a need to update the documentation since you created a command to create the config file with the default configuration of the host machine's ip. 

The only thing that could go wrong if someone touched the configuration of Homestead/Vagrant and could have another host IP address, but maybe if they did that they should know the correct IP and change it in the config file.

I found that command to show the host machine's IP like this :
Retrieve the external ip of the host machine (from this SO : https://stackoverflow.com/a/44873282/2018745)
```
➜  route -n | grep 'UG[ \t]' | awk '{print $2}'
10.0.2.2
```

But that's maybe too unreadable to put in the documentation ^^'

And also regarding my interrogation on opening the 23517 port on Homestead. I think it's irrelevant since we are trying to access the host machine on the 23517 port not specially passing the request through Homestead 23517 port.

**Comment by laemol** [comment] 2021-01-10 12:21
@freekmurze the latest version of the package has fixed it, thanks! Really like Ray btw nice job!
