### ISSUE TITLE
Won't print a string?

### ISSUE THREAD

**Issue by webdevhayes** [spatie/ray#186] opened 2021-01-17 15:43 UTC
**Describe the bug**
Using a simple assignment of a string it won't output anything to ray but dd does just fine.

**Versions**
1.5.0

You can use `composer show` to get the version numbers of:
spatie/ray                         1.11.0 
spatie/laravel-ray                 1.6.1 

PHP version:
Laravel version (if applicable): 7.4.14

**To Reproduce**
```
$image = "<img";
rd($image); or ray($image);
```

**Expected behavior**
Should print the string to the ray app.

**Screenshots**
![Screenshot 2021-01-17 at 15 39 01](https://user-images.githubusercontent.com/101506/104847895-565d4500-58da-11eb-9121-174ac2764a12.png) - dd prints
![Screenshot 2021-01-17 at 15 39 06](https://user-images.githubusercontent.com/101506/104847896-56f5db80-58da-11eb-9531-758d96fbd37c.png)
![Screenshot 2021-01-17 at 15 40 45](https://user-images.githubusercontent.com/101506/104847912-65dc8e00-58da-11eb-85d0-2179db214b03.png)

**Desktop (please complete the following information):**
 - OS: Mac Big sur
 - Version 11.01
 
 **Additional context**
dd seems to print the string just fine like in the screenshot. The code is inside a helper file. I have tried ray and rd inside blade with dd and it doesn't print but dd does.

**Comment by freekmurze** [comment] 2021-01-18 00:06
I could reproduce this. "img" gets displayed, "<img" does not.

**Comment by webdevhayes** [comment] 2021-01-18 08:48
Thanks @freekmurze

**Comment by Tarpsvo** [comment] 2021-01-18 14:31
I have the same issue with XML.

Whenever I try to render an XML string, I think it parses it as HTML (or strips all tags?) and only the XML key values are displayed.

For example:
```
<?xml version="1.0"?>
<SomethingSomething>
  <Test>123</Test>
</SomethingSomething>
```

Will be displayed as `123` in Ray app.

**Comment by AdrianMrn** [comment] 2021-01-18 14:55
We've found the cause and are looking for a solution. Our fix for this might be slightly delayed because of Laracon Online.

**Comment by freekmurze** [comment] 2021-01-19 13:14
This will be fixed in the next release of Ray.

**Closed by freekmurze** 2021-01-19 13:14 UTC
