### ISSUE TITLE
Pinned Icon to taskbar in Windows vanishes after update

### ISSUE THREAD

**Issue by SlyDave** [spatie/ray#246] opened 2021-01-25 16:28 UTC
**Describe the bug**
When you update Ray, any pinned taskbar Icon vanishes.

**Versions**
Ray version: 1.9.0

- spatie/ray package version: 1.17.0
- spatie/laravel-ray package version: 1.9.1 

PHP version:
Laravel version (if applicable): 7.4.11

**To Reproduce**
Steps to reproduce the behaviour:
1. Load Ray
2. Right click Ray icon on taskbar, and select Pin to taskbar
3. Update Ray
4. Ray icon vanishes from taskbar

**Expected behaviour**
When updating Ray for it's associated pinned Icon not vanish from taskbar

**Screenshots**
![image](https://user-images.githubusercontent.com/1842611/105734141-3b1db580-5f2a-11eb-825b-148c4cfd9bdf.png)

**Desktop (please complete the following information):**
 - OS: Windows Pro 10
 - Version 20H2 (19042.746)

**Comment by AdrianMrn** [comment] 2021-03-31 14:21
I think this is caused by [this issue in electron-builder](https://github.com/electron-userland/electron-builder/pull/5312), which should be fixed now. I'm not sure what version it was included in, so in Ray it should either be fixed already, or after this version.

**Closed by AdrianMrn** 2021-03-31 14:21 UTC
