### ISSUE TITLE
Memory leak on Windows

### ISSUE THREAD

**Issue by basepack** [spatie/ray#458] opened 2021-05-27 13:42 UTC
**Describe the bug**
- Two hours ago I started Ray and used it for an hour, frequently using Ctrl + Shift + C to clear it completely
- I was away from keyboard for half an hour and came back and noticed everthing was not as snappy as before in Windows itself. Checked the taskmanager (see screenshot) and saw Ray eating all memory it could find.
- As you can see in the screenshot, ray was not accumulating new errors, the scroll handle within the Ray app is still pretty big.

**Versions**
- spatie/ray package: latest
- spatie/laravel-ray package: latest 
- PHP: 8.0
- Laravel: latest

**To Reproduce**
I do not know how to reproduce, not happening before.

**Screenshots**
![image](https://user-images.githubusercontent.com/939500/119836036-ae97f980-bf01-11eb-966d-c95c8569707a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 
 **Additional context**
I am running this same version of the Windows Ray app for at least a week I think. 
I run `composer update` frequently, last time was yesterday so I should have the newest version of the Laravel Ray package too.

**Comment by genesiscz** [comment] 2021-05-28 18:00
It's actually so hard to even restart the app and clear the queue because it gets stuck way before I can even try. This thing is so slow especially when I forgot I put it there for like an hour while debugging :(

**Comment by basepack** [comment] 2021-05-29 05:21
@genesiscz that's true for Ray and also other Electron apps on Windows. Closing Ray is not enough to stop all Ray processes, they just stay active and the window is hidden. I have to use the task manager to really stop all processes. 

But I think it is typical for Electron apps as HELO behaves the same.

**Comment by freekmurze** [comment] 2021-05-29 09:05
Duplicate of #210

**Closed by freekmurze** 2021-05-29 09:05 UTC
