### ISSUE TITLE
Unable to run global-ray install

### ISSUE THREAD

**Issue by jonathan-dejong** [spatie/ray#648] opened 2022-03-07 09:43 UTC
**Describe the bug**
Trying to install `global-ray` on my CentOS remote dev env using this https://spatie.be/docs/ray/v1/installation-in-your-project/framework-agnostic-php#content-global-installation

I've got a sudo user but not using the root user (as one should not).
When I've installed it through composer I can run:
`global-ray install` which will then result in:

`Warning: file_put_contents(/etc/php.ini): failed to open stream: Permission denied in /home/jonathan.dejong/.config/composer/vendor/spatie/global-ray/src/Support/PhpIni.php on line 36
   ❌ Unable to update PHP ini.`

If I try to run it with sudo I get this weird one:
`sudo: global-ray: command not found`

I tried resolving it by actually installing global-ray through composer for the root user as well but no dice. 

I did eventually solve it by running sudo with current PATH:
`sudo -E env "PATH=$PATH" global-ray install`

However that only resolves the installation issue. 
Now you are instead faced with this when trying to run php (a website):
```
Warning: Unknown: failed to open stream: Permission denied in Unknown on line 0

Fatal error: Unknown: Failed opening required '/home/jonathan.dejong/.config/composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php' (include_path='.:/usr/share/pear:/usr/share/php') in Unknown on line 0
```

Please help as I do not know why this install differs from all the others I've run for this dev env.

**Versions**
Ray version (you can see this in "About Ray"):
1.19.0
PHP version:
7.4.26

**To Reproduce**
Try to install global-ray on a non-root user in a remove env. (specifically CentOS)

**Expected behavior**
Expecting the two install commands to work as they are documented.

**Desktop (please complete the following information):**
 CentOS Linux release 7.9.2009 (Core)
 
 **Additional context**

**Comment by freekmurze** [comment] 2022-03-07 11:34
I don't have access to a CentOS environment, so I can't test this out. I'd accept a PR that solves this for you.

That fatal error you're getting can be solved like this: https://github.com/spatie/global-ray#troubleshooting

**Comment by jonathan-dejong** [comment] 2022-03-07 12:00
Hi @freekmurze  thank you for a very quick response :) 

Yes I've resolved it already by removing that line from my php.ini so all good there.
Will see what I can work out with my friends here on why this happens.

Just to be clear on the process if I have a remote server. This is my interpretation of what is needed:

**Locally**
- Install the Ray app
- Connect it to the remote
- Start developing using the ray methods etc (developing on remote using SSH extension in VS Code)

**Remote**
- Install Global ray composer package
- Run the global-ray install
- Done.

That should be enough yes?

**Comment by freekmurze** [comment] 2022-03-07 13:27
That's correct!

**Comment by freekmurze** [comment] 2022-03-16 21:10
Duplicate of #16

**Closed by freekmurze** 2022-03-16 21:10 UTC
