### ISSUE TITLE
Sending many items at once can freeze Ray

### ISSUE THREAD

**Issue by xavi7th** [spatie/ray#184] opened 2021-01-17 06:00 UTC
**Describe the bug**
The ray app seems to freeze when ever I launch it. The "+" sign at the top does not come active and my scripts take forever when I have calls to ray() in them. When the scripts finally do run, there is no output in ray and ray becomes unresponsive. I have to force quit it to close it.

I have restarted and updated the app a few times and still it's the same.

**Versions**
Ray version (you can see this in "About Ray"): Version 1.5.0 (1.5.0)

You can use `composer show` to get the version numbers of:
- spatie/ray package version:  1.6.1   
- spatie/laravel-ray package version (if applicable):  1.4.0 

PHP version: 7.4.8
Laravel version (if applicable): 7.30.1

**To Reproduce**
1. put a ray() call in your controller
2. make a request
3. Requests takes a very long time and when it is done there is no output on ray. Also ray is frozen

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.5
 
Thanks for a great app.

**Comment by freekmurze** [comment] 2021-01-17 11:57
I can't seem to reproduce this behaviour. Could you create a minimal app that demonstrates this issue for me to look at?

**Comment by webdevhayes** [comment] 2021-01-17 15:35
I experienced this once. It was because I had left a ray() in my code and it had been printing a hell of a lot to the app. Then when I went to the app I couldn't do anything with the app and had to force close it. Just maybe a thought as possible reason.

**Comment by freekmurze** [comment] 2021-01-18 00:09
I tried to reproduce this here by sending two large object to Ray.

https://github.com/spatie/laravel-ray-demo-app/blob/c92af9054c59344dda923cf2714a0ed530fdc356/routes/web.php#L18-L22

Both `app` and `request` are displayed in ray and the page loaded fine and very quickly.

**Comment by xavi7th** [comment] 2021-01-18 05:21
@freekmurze I think I just figured out why it freezes. @webdevhayes comment pointed me in the right direction. The routes in question happen to have a lot of queries and this problem started added the ray()->showQueries() to them. Sending the query data seems to cause the ray app to freeze, not sure why yet though. 

Once the app got frozen, trying to quit and restart seems not to close the previous "freeze" and so this "restarted instance" appears to still be waiting for the previous instance to "unload? or release the port?". I'm not sure which or if either.

Anyways I can confirm that the ray app is working fine when I let it stew a bit (overnight on both occasions) after quitting it and then restarting it and working on other routes.

Thanks for your time.

**Comment by freekmurze** [comment] 2021-01-18 07:28
@AdrianMrn how would you go about solving this one?

**Comment by AdrianMrn** [comment] 2021-01-18 15:05
I've create an issue on the internal repository to track some possible performance improvements we could do.

**Comment by oliverhermanni** [comment] 2021-01-20 08:25
I had similar issues, when displaying large objects in a foreach()-loop. The Ray app seems to get quite slow after that and needed to get restarted. Hadn't the time yet, but I was thinking about writing some custom functions like 

`ray($x)->once()` - only display $x once 
`ray($x)->times($i)` - display $i items of $x
`ray($x)->after($i)` - display $x after $i iterations

Hadn't time to do this yet, though.

**Comment by webdevhayes** [comment] 2021-02-09 13:24
Hey @freekmurze when is this going to be resolved? I am hitting this issue very regularly now I am working with large data sets and currently I am unable to use ray because of this issue. I have to close ray down which defeats the purpose of using ray as I cant see data any more :(

**Comment by patinthehat** [comment] 2021-02-09 13:37
I wonder if this is related to the amount of script & css that the [HtmlDumper sends](https://github.com/symfony/var-dumper/blob/93c1914af9c0619294d867a0fa346d5ea6b7d707/Dumper/HtmlDumper.php#L163-L778).  I'd have to do some debugging, but it seems like it's possible that a significant amount of data is sent when using the [var dumper](https://github.com/symfony/var-dumper).

**Comment by AdrianMrn** [comment] 2021-03-31 15:03
@patinthehat It seems the problem is happening because React can't keep up with the big amount of data it has to render. I'm now removing the scripts & css as you mentioned, which seems to speed it up slightly, but still doesn't completely fix the issue.

Any other advice or pointers would be greatly appreciated, in the meantime I'll continue debugging using the performance graph 🙈

**Comment by patinthehat** [comment] 2021-03-31 15:38
@AdrianMrn what if you measured the rate of incoming payloads along with taking the size of the payloads into account?  

For example, if the app is receiving more than 5 req/sec, or more than 2kb/sec, or 5kb within the last 7.5 sec (or whatever numbers work), render text/empty placeholders for the payloads instead of the actual data.

That would cause the display to scroll more quickly, thus handling a large amount of payloads/data more efficiently.  You can then only render only the visible payloads once you reach the end of the array/whatever holds the actual payload data (the last few items).

Thoughts?

**Comment by AdrianMrn** [comment] 2021-03-31 15:43
I kinda like the idea, but I feel like I should first try to solve the root cause of the issue before accepting that React just can't render the data that fast and finding workarounds.

In the end it's _only some characters being rendered, which really shouldn't be an issue at all for a modern Macbook Pro.

Thanks for thinking along with me!

**Comment by patinthehat** [comment] 2021-03-31 16:02
@AdrianMrn In my opinion, the root cause _is_ Ray trying to render everything, even payloads that it doesn't need to.  Maybe dropping the idea of measuring incoming payloads is better - and go with rendering only what's absolutely necessary and visible.

The other thought I've had on this topic is that perhaps a simplified rewrite of `VarDumper` would help - send less data from the client and do more of the work on the app side, giving you more control over what's displayed.

I'm game to do an experimental `VarDumper` rewrite if you agree that it might be worthwhile.

**Comment by AdrianMrn** [comment] 2021-03-31 16:29
Hold that thought for a bit, I'll try doing another version of your idea of not rendering everything, by using [react-virtualized](https://github.com/bvaughn/react-virtualized)

**Comment by AdrianMrn** [comment] 2021-04-01 14:44
I'm dropping the above idea for now, since calculating the height of items based on their content turns out to be a lot more difficult than I anticipated :)

The -what I thought were minor- performance improvements in the last update seem to have done quite a lot already, at least on my machine. Can someone else try a payload they know froze their Ray again, and see if it works better now?

Sending a continuous stream of data could still brick the application if you don't include new screens every so often, we'll continue improving on this with future releases.

**Comment by patinthehat** [comment] 2021-04-01 15:01
In my tests, `v1.14.7` seems to perform better then previous versions with a large number of payloads on Linux.  It's definitely more responsive.

**Comment by nathanjansen** [comment] 2021-04-05 08:13
I've experienced something similar with showQueries() where a lot of queries are being pushed to Ray. Of course this is also a performance issue within my own app, but I thought using Ray would actually help me solve this problem. As Debugbar from Barryvdh was not very useful in this case. Or at least I thought Ray was more applicable :)

What happened is that the amount of queries was so much it kept on filling Ray. After a while Ray got sluggish, then I added a new screen and it was fast again. So for me it did not freeze, but to use Ray again I had to completely restart it.
Not exactly the same problem as the OP, but still not what I expected.

_What I expected:_
What I had expected was more of an approach like Debugbar where you can simply see all the executed queries, and quickly see which are using up most of the time/resources. What I eventually did was break the application after one iteration, that way I was able to keep Ray running. And somewhat see which queries where taking a lot of resources. But it feels like a lot more work than it would have been with Debugbar.

As a second thought, maybe me thinking of Ray as a sort of framework agnostic Debugbar is wrong. And possibly xdebug would be my actual savior in this case :) Still I believe that Ray could do all of this. I at least see its potential.

I am very curious where this thread will lead us.

**Comment by snapey** [comment] 2021-04-22 19:03
The speed if ray is really doing my head in.  Its so slow to smooth scroll each entry and then if you accidentally leave something like show queries in a loop, it can be slow scrolling for like 20 minutes or more, at each posted item it gets slower and slower and slower.  If it eventually finishes I hit control-L and then its all right for a bit.  I just accidentally dumped about 1000 results to ray and after about an hour of doing something else I had to just quit the app and start again.

Its a nice tool, but what I want is the speed of beyondco.de dump server

**Comment by AdrianMrn** [comment] 2021-04-23 07:11
In the next minor version we're adding a setting to disable the autoscroll and we're virtualizing the log list. This means a lot less items will be rendered at any given point.

We promise we're still actively working on improving the performance of Ray every week, and we appreciate your feedback!

**Comment by AdrianMrn** [comment] 2021-07-22 13:26
1.16.0 includes virtualised lists and should fix this issue for most users. Feel free to open a new issue if the problem persists after updating to 1.16.0

**Closed by AdrianMrn** 2021-07-22 13:26 UTC

**Comment by WebKenth** [comment] 2023-03-20 06:39
@AdrianMrn 

![image](https://user-images.githubusercontent.com/13419123/226264831-8fe7dff6-acb4-42fe-90b0-0a3a55f8aada.png)

My entire Ray has crashed from dumping too many times 

Everytime i opened a new tab it tried to reload the entire stack of messages into a new window, opening too many windows caused it to crash

Any way to can "clear" all data in the Ray application to avoid this?
Do wish we had a "Clear History" option on opening a new window to avoid this
