### ISSUE TITLE
No more working

### ISSUE THREAD

**Issue by damms005** [spatie/ray#892] opened 2024-02-11 20:28 UTC
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
Sorry I know "not working" is vague but I do not know how best to say it.

```
Route::get('/r', function () {
    ray('of light');
    return "ray('of light')";
});
```

I see the string `ray('of light')` in my browser when I visit the route but nothing in Ray app. 

Browser view:
![image](https://github.com/spatie/ray/assets/9839355/7503f518-a31d-4b60-a9a9-1b7bf74d53e0)

Ray  app view:
![image](https://github.com/spatie/ray/assets/9839355/f9cd989c-f128-4086-9b9b-b735240b60fa)

**Versions**
v2.7.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.39.0
- spatie/laravel-ray package version (if applicable):  1.33.0

PHP version: 8.1.27
Laravel version (if applicable): 10.28.0

**To Reproduce**
1. In route, do `ray('anything')`
2. Ray app doesn't show anything

**Expected behavior**
Ray app should show ray stuff

**Screenshots**
Browser view:
![image](https://github.com/spatie/ray/assets/9839355/7503f518-a31d-4b60-a9a9-1b7bf74d53e0)

Ray  app view:
![image](https://github.com/spatie/ray/assets/9839355/f9cd989c-f128-4086-9b9b-b735240b60fa)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version:

```uname -a
Linux damms005-HP-Laptop-15t-dy200 5.15.0-92-generic #102~20.04.1-Ubuntu SMP Mon Jan 15 13:09:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by timvandijck** [comment] 2024-03-04 09:07
@damms005 could you tell me what distro you are using?

**Comment by damms005** [comment] 2024-03-05 04:58
Zorin OS 16.3

**Comment by RhysLees** [comment] 2024-04-19 09:27
Im also facing this issue. There is no output at all, i've removed ray and installed again but that has not solved the issue.

Im running:
Mac M2 Air
Ray 2.7.5
laravel-ray 1.36.1

**Comment by damms005** [comment] 2024-06-21 00:12
Now also happening on my MBP M3. Was working but now stopped working completely.

**Comment by damms005** [comment] 2024-07-27 14:15
This is now a no-op issue lol.

Finally switched to Herd dumps (I think only on Pro?)

Sad, but oronic that spatie has best-in-class open source projects by ray, paid, gets this kind of attention.

**Comment by smoetje** [comment] 2024-08-10 20:24
Same problem here. I can't get it working with Sail. I'm using Ubuntu Desktop 22.04 & followed the instructions,
Tried Ray configuration with Homestead instead to try out this way and this works like a charm (however it's not my preferred environment)

With Docker (after reconfiguring following the documentation) I'm not getting anything: no response at all from Ray app.

Linux 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Docker version 27.1.1, build 6312585

**Comment by smoetje** [comment] 2024-08-10 21:30
> Same problem here. I can't get it working with Sail. I'm using Ubuntu Desktop 22.04 & followed the instructions, Tried Ray configuration with Homestead instead to try out this way and this works like a charm (however it's not my preferred environment)
> 
> With Docker (after reconfiguring following the documentation) I'm not getting anything: no response at all from Ray app.
> 
> Linux 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux Docker version 27.1.1, build 6312585

After further browsing the issues I found the reason: UFW was active (it wasn't before when using in the past).
By adding sudo ufw allow 23517 it works now. May be useful to mention UFW in the docs, saves time...

**Comment by damms005** [comment] 2024-08-12 15:21
@smoetje's suggestion or Ray can auto-detect such blockers and show a notice to the user with suggestion/possible workaround/fix.

**Comment by hapidjus** [comment] 2024-09-09 15:59
I've also started having problems using Ray with Docker and WSL2
The strange thing is that if I trigger it from the terminal in WSL2( running tests that make use of ray() ) it works, but using the browser on the host machine does not work. I've tried all possible variations of domains and IPs (host.docker.internal, gateway.docker.internal, 192.168.1.67, ...)

**Comment by timvandijck** [comment] 2024-12-02 09:17
I'm going to close this issue for now as it has become a collection of different issues.

In essense most problems will have the same cause: your PHP project not being able to send an HTTP call over port 23517 to localhost.

This can be caused by:
- A firewall blocking the port.
- Antivirus blocking the port.
- The port being in use by an other application (it would be a big coinsidence though).

Or it could be due to some extra steps you are missing to make Ray compatible with your setup:
- Using WSL in Windows: https://myray.app/docs/environments/homestead
- Using Homestead or an other type of VM: https://myray.app/docs/environments/homestead
- Using Docker: https://myray.app/docs/environments/docker

People who are still experiencing problems and want help can open a new issue so we can handle it case by case.
We'll also investigate if we can improve anything on our side to help detect these types of issues.

**Closed by timvandijck** 2024-12-02 09:17 UTC

**Comment by damms005** [comment] 2024-12-02 10:08
I think you should have first "improve anything on our side to help detect these types of issues" before closing this, and then *after* that should be "People who are still experiencing problems and want help can open a new issue".

**Comment by timvandijck** [comment] 2024-12-02 13:08
@damms005 I see where you are coming from. The thing is that this issue has become a bucket of "it does not work on my machine" messages and I want to help every person individually, and I personally think that works better on a case by case basis.
