### ISSUE TITLE
Ray doesn't start on windows 10

### ISSUE THREAD

**Issue by pbruelemans** [spatie/ray#371] opened 2021-03-16 12:47 UTC
After the latest update of Ray, the app doesn't seem to start anymore.  
I tried reinstalling it (downloaded the installer again), rebooting, cleaning the folders \Appdata\local\ray and \appdata\roaming\ray... Nothing seems to work.
When I start ray, nothing seems to happen, but there are ray processes running in task manager.

**Versions**
I was using the latest version.  But now have tried reinstalling it with the setup file: ray setup 1.14.1

Output of composer show:
spatie/laravel-ray                   1.17.1         
spatie/ray                           1.21.2        

PHP version:
PHP 7.4.8
Laravel 8.32.1

**Desktop (please complete the following information):**

Windows  20H2 (os build 19042.804)

**Comment by desaintflorent** [comment] 2021-03-16 13:45
I just installed Ray 1.14.2 on my brand new macOS M1 MacBook Air and ray doesn't show any window too. I can see the app icon at the bottom but nothing else.

**Comment by tobimori** [comment] 2021-03-16 13:50
Confirming this issue on Intel Mac with Big Sur / macOS 11.2.3

**Comment by AdrianMrn** [comment] 2021-03-16 14:08
I changed some thing in how and where the app is displayed in 1.14.1. Could you check if the app is rendering on a different display? Is there anything special about your setup, eg clamshell mode or a lot of different monitors?

**Comment by pbruelemans** [comment] 2021-03-16 14:09
> I changed some thing in how and where the app is displayed in 1.14.1. Could you check if the app is rendering on a different display? Is there anything special about your setup, eg clamshell mode or a lot of different monitors?

I am using 3 monitors. But I cant see the app on any of them.

**Comment by AdrianMrn** [comment] 2021-03-16 14:11
@pbruelemans Could you create a new index.js file anywhere on your pc and paste the following code into it:
```js
console.log(process.platform);
```
then use `node index.js` to run it, and send me the output please?

**Comment by AdrianMrn** [comment] 2021-03-16 14:16
To get me some more debugging information, could you also follow these steps please:

**On Windows:**
- Open your cmd/powershell
- Run `cd C:\Users\Adriaan\AppData\Local\Programs\Ray` (or wherever the app is installed on your system, don't forget to at least change your user directory)
- Run `.\Ray.exe`
- See if Ray starts up, and copy+paste the output of the command here

**On MacOS:**
- Open your terminal
- Run `cd /Applications/Ray.app/Contents/MacOS`
- Run `./Ray`
- See if Ray starts up, and copy+paste the output of the command here

**Comment by pbruelemans** [comment] 2021-03-16 14:20
output for "node index.js":   Win32

Output for ray.exe:

15:18:41.913 > Checking for update
15:18:42.364 > Update for version 1.14.2 is not available (latest version: 1.14.2, downgrade is disallowed).
15:18:42.372 > checkForUpdatesAndNotify called, downloadPromise is null

**Comment by tombenevides** [comment] 2021-03-16 14:26
@AdrianMrn I'm having this same problem and when I did the powershell steps you listed, I got this:

![image](https://user-images.githubusercontent.com/18440704/111324554-42676280-8641-11eb-848c-463924dd360b.png)

It's stuck in this for a few minutes and nothing happened so far.

OS: Windows 10 Pro v20H2
Ray: v1.14.2

**Comment by AdrianMrn** [comment] 2021-03-16 14:27
All right, I think this means it's rendering in a spot you can't reach it. Can you right click it on your taskbar and maximize it?

**Comment by pbruelemans** [comment] 2021-03-16 14:28
> All right, I think this means it's rendering in a spot you can't reach it. Can you right click it on your taskbar and maximize it?

It doesnt show in the taskbar of system tray. It also doesnt show up when i use ALT +TAB

**Comment by AdrianMrn** [comment] 2021-03-16 14:31
Does the app show up if you change the resolution of your monitor, or unplug 1 monitor?

**Comment by tombenevides** [comment] 2021-03-16 14:39
When I shutdown my other monitors and run Ray.exe again, the output was the same as @pbruelemans and stilll no ray screen opened. In the task manager, I can see 2 background processes of ray but... nothing more. (Not listed in the "Apps" section and nothing in the ALT+TAB as well) 

![image](https://user-images.githubusercontent.com/18440704/111327174-88252a80-8643-11eb-86a9-c79f5a0881b8.png)

**Comment by pbruelemans** [comment] 2021-03-16 14:39
I just upluggen al my monitors. so only laptop screen now. No change. Tried reïnstalling it.  The installer first says that ray is already running and if I want to close ray. I confirm to close ray. install starts, but after that nothing seems to happen. I dont get a confirmation dialog that the install succeeded.  
Ray seems to be installed , but when I start it, I dont get a window

I get exactly the same as @tombenevides

**Comment by AdrianMrn** [comment] 2021-03-16 14:45
Thanks a bunch for helping me debug this so far. I'm now deploying 1.14.3 which has a possible fix for this issue. It should be available for you in about 10 minutes.

**Comment by AdrianMrn** [comment] 2021-03-16 14:56
1.14.3: https://spatie.be/products/ray/download/windows/latest

**Comment by tombenevides** [comment] 2021-03-16 15:02
Great. Everything working fine! Thank you @AdrianMrn \o

**Comment by pbruelemans** [comment] 2021-03-16 15:04
![image](https://user-images.githubusercontent.com/80755835/111331524-44e1b080-8671-11eb-8a8d-a63251cde457.png)

**Comment by AdrianMrn** [comment] 2021-03-16 15:06
Hahaha my pleasure, glad this is working for you again. Let me know if you run into any other issues, or if you have any suggestions for us! :)

**Closed by AdrianMrn** 2021-03-16 15:06 UTC

**Comment by desaintflorent** [comment] 2021-03-16 16:33
I can confirm that's it's working on macOS Big Sur too after the fix ! Thank's

**Comment by AdrianMrn** [comment] 2021-03-18 10:14
I'm releasing 1.14.5 which changes something about this solution, because it seems to have caused a side-effect (https://github.com/spatie/ray/issues/376). Please let me know if this causes any other issues for you!

**Comment by desaintflorent** [comment] 2021-03-18 11:32
Working on M1 macOS Big Sur

**Comment by tombenevides** [comment] 2021-03-18 13:37
Working on Windos 10

**Comment by AdrianMrn** [comment] 2021-03-18 14:17
Great, thanks for checking!
