### ISSUE TITLE
Ray not able to handle bulk dump

### ISSUE THREAD

**Issue by lovekrissh143** [spatie/ray#325] opened 2021-02-11 09:16 UTC
**Describe the bug**
I'm trying to dump the response generated from the middleware

and while dumping it sends the generated response multiple times 

which makes the application like 60s Ford Falcon. 

I've fairly good system which can output good performance but this dump makes the app feels hanged.

I'm using the latest Spatie release for laravel-ray and ray.

**Versions**
php 7.4.14
laravel 8.27
composer 2.0.9
spatie/laravel-ray  1.12.6 
spatie/ray  1.19.3
App   1.12

**To Reproduce**
Just dump the response or some large bulk of data, you'll get it.

**Expected behavior**
Could display a loading status instead of blocking user or use performance boost.

**Screenshots**
![code](https://user-images.githubusercontent.com/48975027/107618193-2efa5d80-6c77-11eb-931e-046206fccfb4.png)
![code2](https://user-images.githubusercontent.com/48975027/107618197-30c42100-6c77-11eb-9ab2-a3a472cdce04.png)

**Desktop (please complete the following information):**
Edition	Windows 10 Enterprise
Version	20H2
OS build	19042.804

Please help @freekmurze .

:)

**Comment by AdrianMrn** [comment] 2021-03-31 15:02
I'm going to close this as a duplicate of https://github.com/spatie/ray/issues/184

**Closed by AdrianMrn** 2021-03-31 15:02 UTC
