### ISSUE TITLE
Changing shortcut keys (open from anywhere) doesnt save

### ISSUE THREAD

**Issue by nick-wilkins** [spatie/ray#50] opened 2021-01-08 12:31 UTC
**Describe the bug**
Changing the shortcut key of CMD + Shift + L doesnt save, and always reverts back to that.

**Versions**
Version 1.0.4 (1.0.4)

**To Reproduce**
1. Go to Ray > Preferences
2. Change the shortcut last letter (ie L)
3. Try using new shortcut (doesnt work, still using old one)
4. Close the app
5. Re-open the app (not saved)

**Expected behavior**
Saved and working

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.7

**Comment by freekmurze** [comment] 2021-01-08 12:45
I could not reproduce this. When changing the hotkey and restart Ray I get the new hotkey.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/483853/104017069-bd327e00-51b7-11eb-98e3-688e8c4fee79.png">


Did you close preferences after changing the hot key?

**Comment by nick-wilkins** [comment] 2021-01-08 12:47
Ahhh, no I did not. I had assumed that (like the select boxes) saving was instantaneous. If I close preferences from the 'x' then it saves ...

**Comment by freekmurze** [comment] 2021-01-08 12:50
We'll save on changing the value (instead of closing prefs) soon. Enjoy Ray!

**Closed by freekmurze** 2021-01-08 12:50 UTC
