### ISSUE TITLE
Copy Query Button

### ISSUE THREAD

**Issue by vicenterusso** [spatie/ray#661] opened 2022-03-21 11:49 UTC
**Describe the bug**
The copy button for queries never worked to me. **I consider a minor** bug because I can select like normal text. Is this a bug that happens on Linux only?

Maybe a KDE specific problem?

**Versions**
Ray version 2.01

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version 21.04

**Comment by AdrianMrn** [comment] 2022-03-22 08:58
Duplicate of https://github.com/spatie/ray/issues/555, sorry we haven't gotten around to fixing this yet!

**Closed by AdrianMrn** 2022-03-22 08:58 UTC
