### ISSUE TITLE
Clicking on "editor link" does not work [Windows 10]

### ISSUE THREAD

**Issue by ndeblauw** [spatie/ray#105] opened 2021-01-11 08:49 UTC
**Describe the bug**
No matter which editor I choose, I always get to see this popup when I click a link in Ray.
![image](https://user-images.githubusercontent.com/4344869/104160517-8f387e00-53f1-11eb-8d50-ce016f916fd0.png)

Strangely it doesn't allow me to "pick from existing installed programmes". Only referred to the Microsoft store, where I cannot find the apps (that I already have installed)

**Versions**
Ray version: 1.0.8.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.5.0
- spatie/laravel-ray package version (if applicable): 1.3.4

PHP version: 7.4
Laravel version (if applicable): 7.30.1

**To Reproduce**
1. Send data to Ray
2. Click on the file link at the bottom of a ray message (to go to editor)
3. See error

**Expected behavior**
Being able to link the link to my IDE

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19042

**Comment by basepack** [comment] 2021-01-11 10:03
Having the exact same issue. I have however setup my code to use Domains like this:
```
            "App\\": "app/App/",
            "Domain\\": "app/Domain/",
            "Support\\": "app/Support/",
```

I am happy to refactor this approach if that will allow Ray to work though.

**Comment by AdrianMrn** [comment] 2021-01-11 13:41
Duplicate of https://github.com/spatie/ray/issues/21, I'm looking into this.

**Closed by AdrianMrn** 2021-01-11 13:41 UTC
