### ISSUE TITLE
Run away memory usage

### ISSUE THREAD

**Issue by SlyDave** [spatie/ray#210] opened 2021-01-19 15:39 UTC
**Describe the bug**
Memory leak? and constant disk activity.

I've had Ray open for about 4 days now, doing nothing more than capturing from log - i.e. not using the ray() command in any code yet.

**Versions**
1.5.1

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.5.5
- spatie/laravel-ray package version (if applicable): 1.3.4

PHP version:
Laravel version (if applicable): 8.21.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Ray
2. Leave it open for ages

**Expected behaviour**
Not to consume all memory and disk activity

**Screenshots**
![image](https://user-images.githubusercontent.com/1842611/105053854-4f187180-5a69-11eb-9e97-9e443d5c8fda.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 19042

**Comment by jimsaartia** [comment] 2021-01-19 18:52
The same happened to me just now after 24 hours of keeping Ray open in the background.
Didn't have enough time to take a better look before everything started crashing when Ray suddenly ate up 10gb+ of ram.
Basically the same info as @SlyDave but spatie/laravel-ray was not used before leaving Ray open. Only used spatie/ray 1.12.0 for some generic PHP. Windows 10 Pro (19041)

**Comment by freekmurze** [comment] 2021-01-20 08:16
Could you check again with Ray 1.7?

**Comment by ndeblauw** [comment] 2021-01-20 08:16
With Ray 1.5.1.0, a similar problem occurs here, not so much on the memory usage (but I didn't run it for ages), but processor power. An idle Ray app often consumes approx 20% of my processor power
![image](https://user-images.githubusercontent.com/4344869/105145963-b123b600-5aff-11eb-8595-0deebbee1d93.png)

But then the good news: I've just installed 1.7.0.0, and Ray is (in idle state) not even in the top 20 of CPU consumers... Meaning it is on average below 1%. Great work guys!

**Comment by jimsaartia** [comment] 2021-01-20 09:46
> Could you check again with Ray 1.7?

Ray 1.7.0.0 now installed and left open in the background

**Comment by SlyDave** [comment] 2021-01-20 09:52
Same, Ray 1.7.0 installed, will report back in a few days :)

**Comment by lbeauvisage** [comment] 2021-01-20 14:54
hi here 

same  problem with RAY 1.7.0 when reduce the app to the Mac dock (on MB Pro 13 M1)

<img width="745" alt="Capture d’écran 2021-01-20 à 15 51 56" src="https://user-images.githubusercontent.com/786319/105191674-a422b900-5b37-11eb-9e18-91ca9d7729ee.png">

<img width="273" alt="Capture d’écran 2021-01-20 à 15 54 05" src="https://user-images.githubusercontent.com/786319/105191767-c0265a80-5b37-11eb-9baf-e6d62bc8dae3.png">

**Comment by SlyDave** [comment] 2021-01-25 16:12
Using Ray 1.7.0 but otherwise the same setup as everything before I've not experienced the issue again.
1.9.0 is available, so I'll try it with that too and report back. @lbeauvisage is 1.9.0 any better for you?

**Comment by AdrianMrn** [comment] 2021-01-26 08:06
1.9.0 doesn't have any major performance improvements yet, sorry. We've got an internal issue open with a number of planned improvements and fixes, I'll update here when we've release (some of) those.

**Comment by lbeauvisage** [comment] 2021-01-26 12:26
I have updated to 1.10 and after running Ray for a morning all seems OK cc @SlyDave.

**Comment by adevade** [comment] 2021-01-28 08:01
![image](https://user-images.githubusercontent.com/1066486/106107434-371aaf00-6147-11eb-8b4b-0eebe0388eba.png)

Still have this issue with latest v1.10.1.0.

**Comment by SlyDave** [comment] 2021-02-16 11:10
Bad news.

Still getting this on 1.12.0.0

Worth noting Ray wasn't "open" it wasn't on the taskbar, or task tray, but this process was in the background.

![image](https://user-images.githubusercontent.com/1842611/108054931-36d74a80-7047-11eb-9824-363a5e52edc9.png)

This is on a laptop, it had the lid closed, but the power settings do not put it to sleep or hibernate, so shouldn't in theory be a contributing factor.

**Comment by noge075** [comment] 2021-02-18 15:02
Hi!
For me the same with 1.12.0.0
![ray-memory-usage](https://user-images.githubusercontent.com/16837514/108374908-bf99e600-7201-11eb-99f1-0787891805ab.png)
My system totally crashed, was really hard to take the screenshot. :)

My laptop went to sleep multiple times, but it only happens a few times in a month. 

Operation system:
Windows 10 Pro 19042.804

I use with laravel homestead and nodejs too at the same time, but this happened with laravel only too. 

PS: Thank you for the software, It's really good, I'm in love with that from the first time.

**Comment by fatihtoprak** [comment] 2021-02-19 23:06
Any update about Macbook M1 ?

**Comment by savage-eagle** [comment] 2021-02-21 19:56
Happening with me as well somethings when using nodejs and laravel homestead.

![image](https://user-images.githubusercontent.com/72709807/108636630-48648c00-7465-11eb-86fe-506504d647e5.png)

Operation system: Windows 10 Pro 18363.1379
Ray version 1.12.0

**Comment by quantumwebco** [comment] 2021-03-03 14:53
Yeah me too, I had ray open for a couple of hours then shut it and it's using about 20gb of ram and 25% of an i7 processor power and the program isn't even open 

![image](https://user-images.githubusercontent.com/12368817/109823689-11923100-7c30-11eb-82bf-851607a8033d.png)

Apart from that this package is absolutely awesome!! One of the best dev tools in my collection

**Comment by AdrianMrn** [comment] 2021-03-03 15:19
I've tried debugging this a couple of times, but can't solidly reproduce the issue, which makes it very difficult for me to find the cause. Has any of you encountered a surefire way to get this issue, without having to wait a couple of hours? Are there any specific ray methods that you're using that seem to cause this more than others? Most of you seem to be using Windows rather than Mac, is that coincidence, or does the problem really not occur to that extent on Mac?

**Comment by quantumwebco** [comment] 2021-03-03 15:34
Why would it hold on to memory allocation when it's been shut down? Is that a separate issue or linked with this?

I don't currently have a mac so unable to test, would be good to get some feedback from mac users to help you debug.

I will do some more testing on windows now and report my findings. I am mostly using ray($arg) to output models or collections. Not using log or dd/dump. It's a Laravel app

**Comment by AdrianMrn** [comment] 2021-03-03 16:46
@quantumwebco Thanks for looking into this with me!

The thing is that the app doesn't close if you simply press the X button, similar to how applications like Slack stay open in the background. You'll see that it's still active in your tray (might have to wait until 1.14.0 for this to always work), and it'll continue accepting requests in the background.

**Comment by quantumwebco** [comment] 2021-03-03 16:55
Yeah I realised that by the end of my comment, "Only when you exit the background task (in task manager or from sys tray icon) does it release memory". I thought it was still holding the allocation units even after exiting the background process (sys tray) but it's not. Killing the background process does release the memory. Sorry, my bad!

I notice a lot of people saying they're using the Laravel version, is that coincidence or an issue with the Laravel package? I'm guessing coincidence

It's odd that it appears to grow exponentially. If I close and then open ray fresh, refresh the page and dump out the models in the loop it goes up by say 5MB per model, if I then refresh again it goes up by nearly 10MB per model etc.

At the mo I'm just remembering to exit from sys tray and reopen every now and then, is there any way to release the reserved memory when you clear history?

Is there anything I can do that would help you debug? I'm working right now so happy to test some things out

**Comment by patinthehat** [comment] 2021-03-04 08:44
@AdrianMrn @quantumwebco I'd be interested to see if this memory usage occurs when using ray with a language other than PHP _(such as [NodeJS](https://spatie.be/docs/ray/v1/installation-in-your-project/nodejs))_.  That'd help narrow down whether or not it's related to the either the `ray` or `laravel-ray` package, or if it's strictly an App-side issue.

**Comment by AdrianMrn** [comment] 2021-03-04 08:47
>is there any way to release the reserved memory when you clear history?

I tried this before, but -on Mac at least- it didn't seem like the memory problem was being caused by the renderer process, but rather the main process. At the same time, I'm debugging https://github.com/spatie/ray/issues/325, which in some cases makes the problem worse.

>Is there anything I can do that would help you debug?

Not sure yet, but I'll let you know if I come across anything I need more info/data on!

>is that coincidence or an issue with the Laravel package?

>I'd be interested to see if this memory usage occurs when using ray with a language other than PHP

I'm not sure, but I'll give it a go with the nodejs package.

**Comment by noge075** [comment] 2021-03-04 09:18
> @AdrianMrn @quantumwebco I'd be interested to see if this memory usage occurs when using ray with a language other than PHP _(such as [NodeJS](https://spatie.be/docs/ray/v1/installation-in-your-project/nodejs))_. That'd help narrow down whether or not it's related to the either the `ray` or `laravel-ray` package, or if it's strictly an App-side issue.

For me was the same problem when I used Ray with NodeJS.

**Comment by quantumwebco** [comment] 2021-03-04 10:24
Just FYI I exited ray completely from the sys tray and then put the computer to sleep when I got to my desk this morning I checked task manager and found this
![image](https://user-images.githubusercontent.com/12368817/109949582-6e92f300-7cd3-11eb-8e28-e6529ad1480e.png)
High power usage and a fair bit of CPU too
In the details tab
![image](https://user-images.githubusercontent.com/12368817/109949759-a6019f80-7cd3-11eb-99e5-76e0531104b0.png)
Not sure if it's helpful?

**Comment by philipmclifton** [comment] 2021-03-11 21:16
I have to close ray every few hours after memory creeps up to 1GB + 

On latest version of Mac operating system on M1 chip.  

Using Laravel package to send events

**Comment by freekmurze** [comment] 2021-04-13 21:16
@philipmclifton Could you check if you can reproduce this error using our M1 build (you can download it at https://myray.app)

**Comment by philipmclifton** [comment] 2021-04-14 07:46
> @philipmclifton Could you check if you can reproduce this error using our M1 build (you can download it at https://myray.app)

Sure, will take a look.

**Comment by adrianb93** [comment] 2021-04-15 02:15
> hi here
> 
> same problem with RAY 1.7.0 when reduce the app to the Mac dock (on MB Pro 13 M1)
> 
> <img alt="Capture d’écran 2021-01-20 à 15 51 56" width="745" src="https://user-images.githubusercontent.com/786319/105191674-a422b900-5b37-11eb-9e18-91ca9d7729ee.png">
> 
> <img alt="Capture d’écran 2021-01-20 à 15 54 05" width="273" src="https://user-images.githubusercontent.com/786319/105191767-c0265a80-5b37-11eb-9baf-e6d62bc8dae3.png">

Exact same issue. My fan has been spinning like crazy non-stop and my Intel MacBook has been super slow. Found out the cause was Ray using up all the CPU resources.

**Comment by philipmclifton** [comment] 2021-04-15 08:27
> @philipmclifton Could you check if you can reproduce this error using our M1 build (you can download it at https://myray.app)

I am seeing large performance boost so far - will be using the app more heavily today and will report if I have any negative news.

**Comment by genesiscz** [comment] 2021-05-29 11:56
Is this getting more attention by any chance?

**Comment by adrianb93** [comment] 2021-06-21 06:18
I would happily agree in the settings to send app usage stats (performance-related) if it helps get to the bottom of these issues.

**Comment by genesiscz** [comment] 2021-07-19 13:45
Yea they literally don't care at this point, what a bummer for a paid product :(

**Comment by freekmurze** [comment] 2021-07-19 15:29
We will be shipping a new version by the end of the week in which we’ve solved a bunch of performance / memory problems.

**Comment by AdrianMrn** [comment] 2021-07-22 07:14
@genesiscz

I understand your frustration and apologise for taking this long to fix a seemingly easily reproducible issue.

Over the last week, we've closed over 20 public and internal issues, fixed a bunch of bugs, added the popularly requested search feature and implemented virtualised lists which will hopefully help with this issue in particular and other performance issues.

We haven't figured out a way yet to cause the bug outlined in this issue in under a couple of hours, which makes it incredibly tedious to debug (every change to the codebase causes a complete refresh of the application, and a wipe of the renderer's memory usage). **If anyone has figured out a way to get it to a point where it's using 1 or multiple GB of RAM within a matter of minutes, please let us know!**

The changelog for the upcoming update can be found here already, you can expect it to hit within the next 48 hours: https://spatie.be/products/ray/release-notes

I'm going to go ahead and optimistically close this issue, feel free to open a new one if memory and CPU issues persist after updating to 1.16.0

**Closed by AdrianMrn** 2021-07-22 07:14 UTC
