### ISSUE TITLE
Linux: No icon for the application

### ISSUE THREAD

**Issue by pascalchevrel** [spatie/ray#58] opened 2021-01-08 13:48 UTC
**Describe the bug**
There is no icon provided by Ray for the system to use it in the Dock

**Versions**
Ray version (you can see this in "About Ray"): 1.0.3

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.2.0
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4.9
Laravel version (if applicable):

**To Reproduce**
1. Launch ray
2. Look at the dock

**Expected behavior**
Ray has an icon in the dock

**Actual behavior**
Ray is displayed as a blank space in the dock

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version [e.g. 22] 20.10
 
 **Additional context**
Tested in the trial version.

**Screenshots**
![Capture d’écran de 2021-01-08 14-43-54](https://user-images.githubusercontent.com/454375/104022443-962c7a00-51c0-11eb-98df-e465d69819d7.png)

**Comment by pascalchevrel** [comment] 2021-01-08 14:09
I assume that it cannot be added to the dock because of the lack of Icon but maybe it's a different issue

**Comment by AdrianMrn** [comment] 2021-01-11 16:14
I'm having a look into this now!

**Comment by AdrianMrn** [comment] 2021-01-12 14:29
This should be fixed in 1.2.2 (will release later today). Please let me know if the icon still does not appear!

**Comment by pascalchevrel** [comment] 2021-01-12 14:37
This is not fixed in 1.2.2, did you mean maybe an upcoming 1.2.3 coming later today?

**Comment by AdrianMrn** [comment] 2021-01-12 14:40
Yup, my bad!

**Comment by pascalchevrel** [comment] 2021-01-12 18:33
@AdrianMrn Adr This is not fixed in 1.2.3, the ticket should be reopened. Thanks.

**Comment by AdrianMrn** [comment] 2021-01-13 09:52
@pascalchevrel How are you launching the app? I'm not very experienced with Ubuntu, so I just double clicked the AppImage file, which properly shows the icon on my vm.

**Comment by pascalchevrel** [comment] 2021-01-13 09:54
I  launch it from a terminal (I confess I haven't tried with double-clicking :)

**Comment by AdrianMrn** [comment] 2021-01-13 09:55
No worries, it should work either way :) I'll report back soon!

**Comment by pascalchevrel** [comment] 2021-01-13 09:58
I tried double-clicking and I still have a blank icon in my dock. The Ray app is also the only one of my apps with no icon added to its window when cycling through open applications in Gnome (shift+alt+tab).

**Comment by AdrianMrn** [comment] 2021-01-13 10:09
whoops, this might have something to do with it 🙈 
![image](https://user-images.githubusercontent.com/12762044/104438027-cd6ba400-558f-11eb-985a-05f9f6b7d8dd.png)

**Comment by AdrianMrn** [comment] 2021-01-13 10:41
This should be fixed in 1.2.4 🤞

**Closed by AdrianMrn** 2021-01-13 10:41 UTC
Labels: bug

**Comment by pascalchevrel** [comment] 2021-01-13 10:45
Yes, it works now

**Comment by AdrianMrn** [comment] 2021-01-13 10:59
Is it pixelated for you too? It's a 1024x1024px png, so I'm not sure what the issue is on my machine.

**Comment by pascalchevrel** [comment] 2021-01-13 11:12
Yes it is very pixelated but if you use such a large bitmap image that sounds logical as the resizing is going to create artifacts. You should either use a smaller image (256 or 128px) or use one in a vector format (SVG). As an indication, I work for Mozilla and we use a 128px icon for Firefox (actually we provide the icon in 16, 32, 48, 64 and 128px sizes but the 128px one is used by the various OS docks)

**Comment by AdrianMrn** [comment] 2021-01-13 13:02
I've tried with a 128 and 256px icon, and it doesn't seem to change a thing. If it's very annoying to you or other users, I'll do some more research into this.

**Comment by pascalchevrel** [comment] 2021-01-13 14:37
Not a big issue, the lack of icon in the dock was a blocker for me, but with the recent linux fixes it makes the app usable so I took a licence :)

**Comment by eboye** [comment] 2021-12-20 05:17
I'm missing the icon on Manjaro, latest version 1.19.0
