### ISSUE TITLE
Undefined method ::payload()

### ISSUE THREAD

**Issue by bognerf** [spatie/ray#319] opened 2021-02-18 11:11 UTC
**Describe the bug**
With `SEND_JOBS_TO_RAY=true` an exception for an undefined method is raised:

```
Call to undefined method MyNamespace\MyJob::payload()
In: vendor/spatie/laravel-ray/src/Payloads/JobEventPayload.php:22
```

**Versions**
Ray version (you can see this in "About Ray"): 1.12.0

- spatie/ray package version: 1.19.5
- spatie/laravel-ray package version (if applicable): 1.12.6

PHP version: 7.4
Laravel version (if applicable): 8.28.1

**To Reproduce**
1. Create a new Job `php artisan make:job Test1`
2. Set `SEND JOBS_TO_RAY=true`
3. Dispatch this job

**Expected behavior**
No exception is raised and the job is displayed in Ray app.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Linux Mint 20.1

**Comment by freekmurze** [comment] 2021-02-18 11:50
Could you create a minimal app that reproduces this issue?

**Comment by ibrainventures** [comment] 2021-02-22 19:03
Hi there, Got the same issue, Herer are some Details from my System (may it helps)...

My Setup:

```
"name": "spatie/laravel-ray",
"version": "1.13.0",

"name": "spatie/ray",
"version": "1.20.0",

```
![grafik](https://user-images.githubusercontent.com/8803626/108756288-9900e580-7548-11eb-807d-90fe157c0a2d.png)

Faked a payload method for debugging ;-) and getting those details:

![grafik](https://user-images.githubusercontent.com/8803626/108756349-acac4c00-7548-11eb-9001-214aacade142.png)

**Comment by freekmurze** [comment] 2021-02-23 06:59
Thanks for reporting. I cannot reproduce this. Please create a minimal app where you see the issue. This would help me debug.

**Comment by freekmurze** [comment] 2021-02-26 09:29
Closing this, as I cannot reproduce this using the latest versions. If you still see this create a minimal app that reproduces this issue.

**Closed by freekmurze** 2021-02-26 09:29 UTC

**Comment by ericlaaper** [comment] 2021-07-05 11:19
I had the same problem.  Sending a request from vue I got an error message back in the vue app. 500 call to undefinded method. The same is stated in te ray app. ›‹

![Schermafbeelding 2021-07-05 om 13 14 58](https://user-images.githubusercontent.com/20456800/124463310-02182580-dd93-11eb-89f2-2165a41f14cb.png)

After 
sending jobs to ray set to false fixes the problem.
The actual job is handled perfectly.
[boten.zip](https://github.com/spatie/ray/files/6763825/boten.zip)
I attached the laravel app. You can test it with postman

**Comment by GardenRouteGold** [comment] 2021-09-23 13:26
I have the same issue in a 
project i work on
