### ISSUE TITLE
SSH error while linking a remote server

### ISSUE THREAD

**Issue by Martenvanurk** [spatie/ray#442] opened 2021-04-29 10:09 UTC
**Describe the bug**
After adding the server with the right credentials, I'm experiencing this error:

`Error: Error invoking remote method 'connectSsh': Error: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR`

**Versions**
1.14.7

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.22.1
- spatie/laravel-ray package version (if applicable): -

PHP version: 7.4
Laravel version (if applicable):

**To Reproduce**
1. Open Ray server panel
2. Add server with the right credentials
3. Klik on the plug to connect to the server
4. See the error above

**Expected behavior**
I was hoping the server was connecting so I can get Ray working 

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: MacOS 11.3 Big Sur
 - Version 11.3
 
 **Additional context**
-

**Comment by lloricode** [comment] 2021-06-21 07:58
same as mine

name | version
-------- | -----
Ray app version | 1.14.7
spatie/laravel-ray      |                           1.20.2 
spatie/ray                   |                      1.26.0 
PHP | 7.4.18 
Laravel Framework  | 8.47.0

![Screenshot from 2021-06-21 15-52-29](https://user-images.githubusercontent.com/8251344/122726986-219a5300-d2a9-11eb-83c9-f1f08bf3c4c6.png)
![Screenshot from 2021-06-21 15-52-38](https://user-images.githubusercontent.com/8251344/122727001-252dda00-d2a9-11eb-9426-e08a9f6365dd.png)

even real remote server same error when using only ssh connection

**Comment by lloricode** [comment] 2021-06-29 00:19
hi @freekmurze, any update on this? thank you

**Comment by benjamin74** [comment] 2021-07-08 19:58
I'm getting the same error:

**Error: Error invoking remote method 'connectSsh': Error: All configured authentication methods failed**

When trying to connect from the desktop UI with a **username + password** (on a non standard SSH port but I'm not sure that's the problem).

It even **looks like the password isn't saved at all** when reopening the connection by clicking on the edit button (it will reopen with the SSH private key path selected, not the password I entered and saved before).

OSX Catalina 10.15.7 (19H1217)

**Comment by benjamin74** [comment] 2021-07-08 20:06
I was making a video to explain the issue and apparently found a workaround to still save my SSH password. So there is really a bug, but there is also a workaround:

https://www.screencast.com/t/xm5Z7ApNNjmR

**Comment by lloricode** [comment] 2021-07-13 05:25
> I was making a video to explain the issue and apparently found a workaround to still save my SSH password. So there is really a bug, but there is also a workaround:
> 
> https://www.screencast.com/t/xm5Z7ApNNjmR

yes, this is also occasional happen to me, but this must be different issue

**Comment by AdrianMrn** [comment] 2021-07-15 09:48
A fix for this will be included in the next release!

**Closed by AdrianMrn** 2021-07-15 09:48 UTC

**Comment by JoshMoreno** [comment] 2021-08-13 16:28
@AdrianMrn Is this fixed? I'm still having this problem on the latest version `1.17.0`.
For what it's worth, I was never able to use tinkerwell (beyondcode electron app) over ssh, so perhaps it's something on my system. I ran brew upgrade in case that was the problem, but no luck. 😭

**Comment by AdrianMrn** [comment] 2021-08-16 11:13
@JoshMoreno The bug outlined in this issue was fixed yes, could you create a new issue with reproduction steps for the issue you are encountering, so we can take a look at it, please?

**Comment by gjportegies** [comment] 2021-11-24 10:58
I'm currently running version 1.18.5 but getting this error as well when trying to connect.

```
Error: Error invoking remote method 'connectSsh': Error: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR
```

Other than @JoshMoreno I am able to connect to the same server and key with Tinkerwell.

**Comment by gjportegies** [comment] 2021-11-24 11:02
I managed to 'fix' the error by converting the private key file from OpenSSH private key format to PEM format. I've found that solution for a simalar issue here: https://slacker.ro/2021/04/15/vscode-sftp-plugin-connecting-with-private-key-erroropenssl_internaldecode_error/

`ssh-keygen -p -m PEM -f ~/.ssh/<private-key-file>`

**Comment by gonzunigad** [comment] 2023-07-20 02:38
i'm having the same problem.
<img width="694" alt="image" src="https://github.com/spatie/ray/assets/1103494/48ac2186-21ba-421a-aa79-61a564f36f73">
<img width="626" alt="image" src="https://github.com/spatie/ray/assets/1103494/033af92d-9571-4d18-a600-192f69da9ef7">

**Comment by JerrelZ** [comment] 2023-07-21 19:15
Same issue here as well.

**Comment by aotearoait** [comment] 2023-08-02 04:26
Having same issue with connecting to forge servers in AWS using SSH Key
