### ISSUE TITLE
Show app on menubar now working

### ISSUE THREAD

**Issue by semiherdogan** [spatie/ray#135] opened 2021-01-13 08:16 UTC
**Describe the bug**
Show app on menubar function not working. It removes icon from duck, but not adding into menubar.

**Versions**
Ray version 1.2.3

**To Reproduce**
1. Go to ray settings
2. Change show app action to on menubar or on both

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.1 (Big Sur)

**Comment by freekmurze** [comment] 2021-01-13 08:19
@AdrianMrn I could reproduce this. The menu item has been set, but it has no icon. In the previous versions it worked. I guess this is caused by some refactoring yesterday.

**Comment by AdrianMrn** [comment] 2021-01-13 09:50
I'm already tracking this in the main repository, I'll report back here once I've found an issue.

It only seems to happen the first time you set it to menu. If you switch to dock and then to menu again, the icon appears. I'll try to fix this today.

**Comment by semiherdogan** [comment] 2021-01-13 09:57
For me menu bar never appears. 

https://user-images.githubusercontent.com/5646041/104436440-a799cb80-559e-11eb-8383-fa420f29912f.mp4

**Comment by AdrianMrn** [comment] 2021-01-13 10:08
Whoops
![image](https://user-images.githubusercontent.com/12762044/104437883-9eedc900-558f-11eb-8179-ed94ba55341d.png)
![image](https://user-images.githubusercontent.com/12762044/104437899-a44b1380-558f-11eb-874d-1ad1588d08ca.png)

**Comment by AdrianMrn** [comment] 2021-01-13 10:40
This will be fixed in 1.2.5, which we will release later today!

**Closed by AdrianMrn** 2021-01-13 10:40 UTC
